BUILD : 1.7.5 (355) BUGS : N/A NOTES : An option to not detect mysql has been added to ./Config
git-svn-id: svn://svn.anope.org/anope/trunk@355 31f1291d-b8d6-0310-a050-a5561fc1590b


git-svn-id: http://anope.svn.sourceforge.net/svnroot/anope/trunk@231 5417fbe8-f217-4b02-8779-1006273d7864

diff --git a/Config b/Config
--- a/Config
+++ b/Config
@@ -324,6 +324,35 @@ echo ""
 
 ####
 
+ok=0
+DEF=yes
+echo "Allow anope to automatically check for mysql libaries?"
+echo "unless you get errors with make, there is no need to"
+echo "change this setting."
+while [ $ok -eq 0 ] ; do
+        echo2 "[$DEF] "
+        if read INPUT ; then : ; else echo "" ; exit 1 ; fi
+        if [ ! "$INPUT" ] ; then
+                INPUT=$DEF
+        fi
+        case $INPUT in
+                n*|N*)
+			MYSQL=
+			ok=1
+			;;
+                y*|Y*)
+			MYSQL="yes"
+			ok=1
+			;;
+                *)
+                        echo "Please enter 'yes' or 'no'."
+                        ;;
+        esac
+done
+echo ""
+
+####
+
 
 ################################################################################
 # Store values
@@ -338,6 +367,7 @@ UMASK=$UMASK
 IRCTYPE=$IRCTYPE
 IRCTYPE_DEF="$IRCTYPE_DEF"
 ENCRYPTION="$ENCRYPTION"
+MYSQL="$MYSQL"
 EOT
 echo "done."
 
@@ -352,6 +382,7 @@ WITH_ENC=""
 WITH_IRCD=""
 WITH_RUN=""
 WITH_PERM=""
+WITH_MYSQL=""
 
 if [ "$BINDEST" != "" ] ; then 
     WITH_BIN=" --with-bindir=$BINDEST"
@@ -378,8 +409,12 @@ if [ "$UMASK" != "" ] ; then
     WITH_PERM=" --with-permissions=$UMASK"
 fi
 
+if [ "$MYSQL" != "yes" ] ; then
+    WITH_MYSQL=" --without-mysql"
+fi
 
-echo "./configure $WITH_BIN $WITH_DATA $WITH_ENC $WITH_IRCD $WITH_RUN $WITH_PERM"
 
-./configure $WITH_BIN $WITH_DATA $WITH_ENC $WITH_IRCD $WITH_RUN $WITH_PERM
+echo "./configure $WITH_BIN $WITH_DATA $WITH_ENC $WITH_IRCD $WITH_RUN $WITH_PERM $WITH_MYSQL"
+
+./configure $WITH_BIN $WITH_DATA $WITH_ENC $WITH_IRCD $WITH_RUN $WITH_PERM $WITH_MYSQL
 
