Possible fix for issue with RequiredLibraries comment check in CMake generation. Also include extra question in Config to ask for extra arguments to the build tool used.
git-svn-id: http://anope.svn.sourceforge.net/svnroot/anope/trunk@2345 5417fbe8-f217-4b02-8779-1006273d7864

diff --git a/Config b/Config
--- a/Config
+++ b/Config
@@ -42,6 +42,7 @@ Run_Build_System () {
 	WITH_PERM=""
 	BUILD_TYPE=""
 	RUN_CC_PL=""
+	EXTRA_ARGS=""
 	GEN_TYPE=""
 
 	if [ "$INSTDIR" != "" ] ; then
@@ -113,9 +114,9 @@ Run_Build_System () {
 			REAL_SOURCE_DIR="$SOURCE_DIR"
 		fi
 
-		echo "cmake $GEN_TYPE $WITH_INST $WITH_RUN $WITH_PERM $BUILD_TYPE $RUN_CC_PL $REAL_SOURCE_DIR"
+		echo "cmake $GEN_TYPE $WITH_INST $WITH_RUN $WITH_PERM $BUILD_TYPE $RUN_CC_PL $EXTRA_ARGS $REAL_SOURCE_DIR"
 
-		cmake $GEN_TYPE $WITH_INST $WITH_RUN $WITH_PERM $BUILD_TYPE $RUN_CC_PL $REAL_SOURCE_DIR
+		cmake $GEN_TYPE $WITH_INST $WITH_RUN $WITH_PERM $BUILD_TYPE $RUN_CC_PL $EXTRA_ARGS $REAL_SOURCE_DIR
 
 		echo ""
 		if [ "$SOURCE_DIR" = "." ] ; then
@@ -125,9 +126,9 @@ Run_Build_System () {
 			echo "Now run make to build Anope."
 		fi
 	else
-		echo "./configure $WITH_INST $WITH_RUN $WITH_PERM $BUILD_TYPE $RUN_CC_PL"
+		echo "./configure $WITH_INST $WITH_RUN $WITH_PERM $BUILD_TYPE $EXTRA_ARGS $RUN_CC_PL"
 
-		./configure $WITH_INST $WITH_RUN $WITH_PERM $BUILD_TYPE $RUN_CC_PL
+		./configure $WITH_INST $WITH_RUN $WITH_PERM $BUILD_TYPE $EXTRA_ARGS $RUN_CC_PL
 	fi
 }
 
@@ -154,6 +155,7 @@ RUNGROUP=
 UMASK=
 DEBUG="yes"
 USE_RUN_CC_PL="no"
+EXTRA_CONFIG_ARGS=
 CAN_QUICK="no"
 SOURCE_DIR=`dirname $0`
 
@@ -288,7 +290,6 @@ done
 INSTDIR=$INPUT
 echo ""
 
-
 ####
 
 OLD_RUNGROUP="$RUNGROUP"
@@ -387,6 +388,16 @@ echo ""
 
 ####
 
+echo "Are there any extra aguments you wish to pass to $BUILD_SYSTEM?"
+echo "(You may only need to do this if $BUILD_SYSTEM is unable to locate"
+echo "missing dependancies without hints)"
+echo2 "[$EXTRA_CONFIG_ARGS] "
+if read INPUT ; then : ; else echo "" ; exit 1 ; fi
+EXTRA_CONFIG_ARGS=$INPUT
+echo ""
+
+####
+
 ################################################################################
 # Store values
 ################################################################################
@@ -400,6 +411,7 @@ RUNGROUP="$RUNGROUP"
 UMASK=$UMASK
 DEBUG="$DEBUG"
 USE_RUN_CC_PL="$USE_RUN_CC_PL"
+EXTRA_CONFIG_ARGS="$EXTRA_CONFIG_ARGS"
 EOT
 echo "done."
 
